image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Docker Compose
    init: |
      docker compose pull || true
    command: |
      docker compose up -d --build
      docker compose ps
      docker compose exec api python init_db.py

ports:
  - port: 8000
    onOpen: open-preview
  - port: 5432
    onOpen: ignore
