"""add users table

Revision ID: c3f96c4f2b52
Revises: 0001_baseline
Create Date: 2025-12-19 15:36:23.876012

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'c3f96c4f2b52'
down_revision = '0001_baseline'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
